"{"
"        \"bool_list\": [false, true, false, true, false, true, false, true, false, true],"
"        \"bool_string_map\": [{"
"            \"key\": false,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": true,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }],"
"        \"enum_list\": null,"
"        \"enum_map\": null,"
"        \"float_list\": [0.0, 7.5, 15.0, 22.5, 30.0, 37.5, 45.0, 52.5, 60.0, 67.5],"
"        \"float_string_map\": [{"
"            \"key\": 0.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 1.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 2.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 3.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 4.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 5.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 6.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 7.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 8.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 9.0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }],"
"        \"float_value0\": 100.0,"
"        \"float_value1\": 1000.0,"
"        \"int_list\": [0, 13, 26, 39, 52, 65, 78, 91, 104, 117],"
"        \"int_string_map\": [{"
"            \"key\": 0,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 1,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 2,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 3,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 4,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 5,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 6,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 7,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 8,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": 9,"
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }],"
"        \"int_value0\": 1234,"
"        \"int_value1\": 6346363,"
"        \"object\": {"
"            \"value\": 487998"
"        },"
"        \"object_list\": [{"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }, {"
"            \"value\": 132123123"
"        }],"
"        \"object_map\": [{"
"            \"key\": \"0\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"1\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"2\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"3\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"4\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"5\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"6\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"7\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"8\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }, {"
"            \"key\": \"9\","
"            \"value\": {"
"                \"value\": 547987"
"            }"
"        }],"
"        \"object_ptr\": {"
"            \"AllTypesChildren\": {"
"                \"value\": 243525235"
"            }"
"        },"
"        \"object_ptr_list\": [{"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }, {"
"            \"AllTypesChildren\": {"
"                \"value\": 234234"
"            }"
"        }],"
"        \"object_ptr_map\": [{"
"            \"key\": \"0\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"1\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"2\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"3\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"4\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"5\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"6\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"7\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"8\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }, {"
"            \"key\": \"9\","
"            \"value\": {"
"                \"AllTypesChildren\": {"
"                    \"value\": 6879"
"                }"
"            }"
"        }],"
"        \"str_value0\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\","
"        \"str_value1\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\","
"        \"string_bool_map\": [{"
"            \"key\": \"0\","
"            \"value\": false"
"        }, {"
"            \"key\": \"1\","
"            \"value\": true"
"        }],"
"        \"string_float_map\": [{"
"            \"key\": \"0\","
"            \"value\": 0.0"
"        }, {"
"            \"key\": \"1\","
"            \"value\": 1.0"
"        }, {"
"            \"key\": \"2\","
"            \"value\": 2.0"
"        }, {"
"            \"key\": \"3\","
"            \"value\": 3.0"
"        }, {"
"            \"key\": \"4\","
"            \"value\": 4.0"
"        }, {"
"            \"key\": \"5\","
"            \"value\": 5.0"
"        }, {"
"            \"key\": \"6\","
"            \"value\": 6.0"
"        }, {"
"            \"key\": \"7\","
"            \"value\": 7.0"
"        }, {"
"            \"key\": \"8\","
"            \"value\": 8.0"
"        }, {"
"            \"key\": \"9\","
"            \"value\": 9.0"
"        }],"
"        \"string_int_map\": [{"
"            \"key\": \"0\","
"            \"value\": 0"
"        }, {"
"            \"key\": \"1\","
"            \"value\": 1"
"        }, {"
"            \"key\": \"2\","
"            \"value\": 2"
"        }, {"
"            \"key\": \"3\","
"            \"value\": 3"
"        }, {"
"            \"key\": \"4\","
"            \"value\": 4"
"        }, {"
"            \"key\": \"5\","
"            \"value\": 5"
"        }, {"
"            \"key\": \"6\","
"            \"value\": 6"
"        }, {"
"            \"key\": \"7\","
"            \"value\": 7"
"        }, {"
"            \"key\": \"8\","
"            \"value\": 8"
"        }, {"
"            \"key\": \"9\","
"            \"value\": 9"
"        }],"
"        \"string_list\": [\"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\", \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\"],"
"        \"string_string_map\": [{"
"            \"key\": \"0\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"1\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"2\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"3\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"4\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"5\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"6\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"7\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"8\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }, {"
"            \"key\": \"9\","
"            \"value\": \"1231asfsdgsrhy4t5243dasfkhgpuhq34gphw9FH072HG}\""
"        }]"
"}";
